from __future__ import annotations

from copy import deepcopy
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class DrillSplitConfig:
    tolerance: float = 0.1
    diameter_decimals: int = 3
    coordinate_decimals: int = 5
    output_prefix: str = "Drill"


DRILL_SPLIT = DrillSplitConfig()


def _object_options(defaults: dict, name: str) -> dict:
    options = {
        key.removeprefix("excellon_"): deepcopy(value)
        for key, value in defaults.items()
        if key.startswith("excellon_")
    }
    options.update({"name": name, "plot": True, "solid": True})
    return options


def group_tools(tools: dict, config: DrillSplitConfig = DRILL_SPLIT) -> list[dict]:
    """Group tools while keeping every group's full diameter span within tolerance."""
    if config.tolerance < 0:
        raise ValueError("Drill merge tolerance cannot be negative")

    sorted_tools = sorted(tools.values(), key=lambda tool: float(tool["tooldia"]))
    clusters = []
    for tool in sorted_tools:
        diameter = float(tool["tooldia"])
        if not clusters or diameter - clusters[-1]["minimum"] > config.tolerance:
            clusters.append({"minimum": diameter, "tools": [tool]})
        else:
            clusters[-1]["tools"].append(tool)

    groups = []
    for cluster in clusters:
        members = cluster["tools"]
        diameter = round(
            sum(float(tool["tooldia"]) for tool in members) / len(members),
            config.diameter_decimals,
        )
        groups.append(
            {
                "diameter": diameter,
                "source_diameters": [float(tool["tooldia"]) for tool in members],
                "drills": [
                    deepcopy(drill)
                    for tool in members
                    for drill in tool.get("drills", [])
                ],
                "slots": [
                    deepcopy(slot)
                    for tool in members
                    for slot in tool.get("slots", [])
                ],
            }
        )
    return groups


def _coordinate(value: float, decimals: int) -> str:
    return f"{value:.{decimals}f}"


def render_excellon(group: dict, config: DrillSplitConfig = DRILL_SPLIT) -> str:
    """Render one grouped tool as a metric decimal-coordinate Excellon file."""
    diameter = group["diameter"]
    decimals = config.coordinate_decimals
    lines = [
        "; Generated by pcb-cam drill splitter",
        "; Source diameters: " + ", ".join(f"{dia:.5f}" for dia in group["source_diameters"]),
        "M48",
        f"METRIC,LZ,0000.{('0' * decimals)}",
        f"T01C{diameter:.{config.diameter_decimals}f}",
        "%",
        "G05",
        "G90",
        "T01",
    ]
    for drill in group["drills"]:
        lines.append(
            f"X{_coordinate(drill.x, decimals)}Y{_coordinate(drill.y, decimals)}"
        )
    for start, stop in group["slots"]:
        lines.append(
            f"X{_coordinate(start.x, decimals)}Y{_coordinate(start.y, decimals)}"
            f"G85X{_coordinate(stop.x, decimals)}Y{_coordinate(stop.y, decimals)}"
        )
    lines.append("M30")
    return "\n".join(lines) + "\n"


def _serialize_group(
    group: dict,
    name: str,
    source_file: str,
    Excellon,
    defaults: dict,
) -> dict:
    obj = Excellon(geo_steps_per_circle=int(defaults["geometry_circle_steps"]))
    obj.default_data = _object_options(defaults, name)
    obj.source_file = source_file
    obj.tools = {
        1: {
            "tooldia": group["diameter"],
            "drills": deepcopy(group["drills"]),
            "slots": deepcopy(group["slots"]),
            "solid_geometry": [],
            "multicolor": None,
        }
    }
    if obj.create_geometry() == "fail":
        raise RuntimeError(f"Could not create grouped drill geometry: {name}")

    data = obj.to_dict()
    options = _object_options(defaults, name)
    xmin, ymin, xmax, ymax = obj.bounds()
    options.update({"xmin": xmin, "ymin": ymin, "xmax": xmax, "ymax": ymax})
    fill_color = defaults.get("excellon_plot_fill", "#C40000bf")
    outline_color = defaults.get("excellon_plot_line", "#750000bf")
    data.update(
        {
            "kind": "excellon",
            "options": options,
            "fill_color": fill_color,
            "outline_color": outline_color,
            "alpha_level": fill_color[-2:] if len(fill_color) >= 2 else "bf",
        }
    )
    return data


def split_excellon_file(
    source_path: Path,
    output_dir: Path,
    Excellon,
    defaults: dict,
    config: DrillSplitConfig = DRILL_SPLIT,
) -> list[dict]:
    """Parse, group, write, and serialize split Excellon drill objects."""
    source = Excellon(geo_steps_per_circle=int(defaults["geometry_circle_steps"]))
    source.default_data = _object_options(defaults, source_path.name)
    if source.parse_file(str(source_path)) == "fail":
        raise RuntimeError(f"Could not parse drill file for splitting: {source_path}")

    groups = group_tools(source.tools, config)
    objects = []
    for index, group in enumerate(groups, start=1):
        name = f"{config.output_prefix}{index}.DRL"
        content = render_excellon(group, config)
        (output_dir / name).write_text(content, encoding="ascii", newline="\n")
        objects.append(_serialize_group(group, name, content, Excellon, defaults))
    return objects
